export type CapabilityGroup = { id: string; title: string; items: string[] };

export const capabilityGroups: CapabilityGroup[] = [
  {
    "id": "01",
    "title": "AI / AI-NATIVE ENGINEERING",
    "items": [
      "AI Lead Engineering",
      "AI-Native Engineering",
      "AI-Native Software Development",
      "AIDLC",
      "AI-assisted SDLC",
      "Vibe Coding",
      "Agentic Coding",
      "Coding Agents",
      "AI-assisted Architecture",
      "AI-assisted Implementation",
      "AI-assisted Debugging",
      "AI-assisted Testing",
      "AI-assisted Documentation",
      "AI Development Workflows",
      "AI Development Loops",
      "Context Engineering",
      "Prompt Engineering",
      "Prompt Design",
      "AI Orchestration",
      "AI Integration",
      "AI Tool Evaluation",
      "AI Model Evaluation",
      "LLM Applications",
      "Generative AI",
      "Applied AI",
      "AI Prototyping",
      "AI Automation"
    ]
  },
  {
    "id": "02",
    "title": "AGENT ENGINEERING",
    "items": [
      "Agent Engineering",
      "Agent-as-a-Service",
      "Agentic Systems",
      "Agentic Workflows",
      "AI Agents",
      "Multi-Agent Systems",
      "Agent Orchestration",
      "Agent Skills",
      "Agent Identity",
      "Agent Context",
      "Agent Memory",
      "Agent Tools",
      "Tool Calling",
      "MCP",
      "Model Context Protocol",
      "Agent Permissions",
      "Agent Evaluation",
      "Agent Observability",
      "Human-in-the-loop",
      "Human-in-the-loop AI",
      "AI Workers",
      "Digital Employees",
      "AI Employee Architecture",
      "AI Workflow Agents",
      "Autonomous Workflow Design",
      "Semi-autonomous Systems",
      "Agent workflows",
      "MCP & agent skills",
      "Human approval"
    ]
  },
  {
    "id": "03",
    "title": "AI WORKFLOW / AUTOMATION",
    "items": [
      "AI Workflow Engineering",
      "Workflow Automation",
      "Business Process Automation",
      "AI Automation",
      "Workflow Orchestration",
      "Workflow Design",
      "Workflow State Management",
      "Event-driven Workflows",
      "AI Pipelines",
      "Automation Pipelines",
      "API Orchestration",
      "Tool Integration",
      "SaaS Integration",
      "System Integration",
      "Webhooks",
      "Data Synchronization",
      "Internal Tools",
      "AI-powered Internal Tools",
      "Business Workflow Systems",
      "Automation Architecture",
      "Integrations"
    ]
  },
  {
    "id": "04",
    "title": "PRODUCT / BUSINESS / STRATEGY",
    "items": [
      "Product Discovery",
      "Product Strategy",
      "Product Thinking",
      "Problem Discovery",
      "Business Problem Analysis",
      "Business Process Analysis",
      "Requirements Engineering",
      "Requirements Analysis",
      "PRD",
      "User Stories",
      "Acceptance Criteria",
      "User Flows",
      "Product Specification",
      "Design Specification",
      "Technical Specification",
      "MVP Design",
      "Rapid Prototyping",
      "Product Validation",
      "Experiment Design",
      "Build vs Buy",
      "RICE",
      "ROI Analysis",
      "Technical Strategy",
      "Product Engineering",
      "Business → Product → Technology",
      "Product → AI → Engineering",
      "Product vision & strategy",
      "Requirements"
    ]
  },
  {
    "id": "05",
    "title": "UX / UI / DESIGN",
    "items": [
      "UX/UI",
      "UX Design",
      "UI Design",
      "User Experience",
      "Interface Design",
      "User Flow Design",
      "Information Architecture",
      "Interaction Design",
      "Product Design",
      "Design Systems",
      "Wireframing",
      "Prototyping",
      "Visual Design",
      "Digital Product Design",
      "Interaction Prototyping",
      "Design Thinking",
      "UX Research",
      "User Journey Mapping",
      "Product UX",
      "Technical UX",
      "AI Product UX",
      "AI Interaction Design",
      "Human-AI Interaction",
      "Interactive Experience Design",
      "UX & user flows"
    ]
  },
  {
    "id": "06",
    "title": "SOFTWARE ENGINEERING",
    "items": [
      "Software Engineering",
      "Software Architecture",
      "System Architecture",
      "System Design",
      "Full-stack Development",
      "Full-stack Delivery",
      "Frontend Development",
      "Backend Development",
      "Web Application Development",
      "API Design",
      "REST APIs",
      "Database Design",
      "Data Modeling",
      "Authentication",
      "Authorization",
      "RBAC",
      "RLS",
      "State Management",
      "Testing",
      "Debugging",
      "Refactoring",
      "Code Review",
      "CI/CD",
      "Git",
      "GitHub",
      "Software Documentation",
      "ADR",
      "Requirements Traceability",
      "SDLC",
      "Agile / Iterative Development",
      "API & database design"
    ]
  },
  {
    "id": "07",
    "title": "PROGRAMMING / TECHNOLOGY",
    "items": [
      "Python",
      "JavaScript",
      "TypeScript",
      "React",
      "Next.js",
      "Flask",
      "PostgreSQL",
      "Supabase",
      "Google Apps Script",
      "REST",
      "JSON",
      "HTML",
      "CSS",
      "Web Applications",
      "PWA",
      "Desktop GUI",
      "Browser Applications"
    ]
  },
  {
    "id": "08",
    "title": "DATA ENGINEERING",
    "items": [
      "Data Engineering",
      "Data Pipelines",
      "Data Processing",
      "Data Extraction",
      "Data Transformation",
      "Data Normalization",
      "Structured Data",
      "Structured Extraction",
      "Data Validation",
      "Data Cleaning",
      "Dataset Engineering",
      "Dataset Construction",
      "Ground Truth",
      "Evaluation Datasets",
      "Hold-out Testing",
      "Data Analysis",
      "Data Research",
      "Multilingual Data",
      "Data Quality",
      "Data Verification",
      "Entity Resolution",
      "Knowledge Bases",
      "Knowledge Graph Concepts",
      "Evidence-based Data",
      "Dataset design"
    ]
  },
  {
    "id": "09",
    "title": "DOCUMENT INTELLIGENCE",
    "items": [
      "Document Intelligence",
      "Intelligent Document Processing",
      "OCR",
      "Visual Document Understanding",
      "PDF Processing",
      "Document Parsing",
      "Table Extraction",
      "Cell Extraction",
      "Structured Document Extraction",
      "Contract Extraction",
      "Contract Intelligence",
      "Evidence Extraction",
      "Source Attribution",
      "Document Verification",
      "Human Verification",
      "Document Classification",
      "Document Workflows",
      "Document Pipelines",
      "Document AI",
      "Multimodal AI",
      "Hotel Contract Intelligence",
      "Hotel Rate Extraction",
      "DMC Knowledge Base",
      "Structured Contract Data",
      "Document Evidence"
    ]
  },
  {
    "id": "10",
    "title": "AI EVALUATION / RELIABILITY",
    "items": [
      "AI Evaluation",
      "Model Evaluation",
      "Agent Evaluation",
      "Prompt Evaluation",
      "Benchmarking",
      "Accuracy Evaluation",
      "Ground-truth Evaluation",
      "Regression Testing",
      "Error Analysis",
      "Root Cause Analysis",
      "Model Comparison",
      "Quality Evaluation",
      "Reliability Evaluation",
      "Cost Evaluation",
      "Latency Evaluation",
      "Confidence / Uncertainty",
      "Human Review",
      "Verification",
      "AI Quality Assurance",
      "AI Testing",
      "Evaluation Pipelines"
    ]
  },
  {
    "id": "11",
    "title": "WEB / DATA EXTRACTION",
    "items": [
      "Web Scraping",
      "Web Data Extraction",
      "Browser Automation",
      "RPC Analysis",
      "Google Maps RPC",
      "Anti-bot Engineering",
      "Scraping Architecture",
      "Data Collection",
      "Large-scale Review Collection",
      "Research Data Collection",
      "Web Research",
      "Structured Web Data",
      "API Reverse Engineering",
      "Reverse Engineering",
      "RPC & web data collection",
      "Protocol analysis"
    ]
  },
  {
    "id": "12",
    "title": "CLOUD / INFRASTRUCTURE / DEVOPS",
    "items": [
      "Cloud Architecture",
      "Cloud Deployment",
      "Google Cloud",
      "Vercel",
      "Supabase",
      "Docker",
      "Linux",
      "CI/CD",
      "Deployment",
      "Production Deployment",
      "Environment Management",
      "Cloud APIs",
      "Storage",
      "Monitoring",
      "Logging",
      "Infrastructure",
      "Infrastructure Design",
      "Production Troubleshooting",
      "Service Integration",
      "API Infrastructure"
    ]
  },
  {
    "id": "13",
    "title": "SECURITY / GOVERNANCE",
    "items": [
      "Security Review",
      "Security Architecture",
      "Access Control",
      "Authorization",
      "RBAC",
      "Row Level Security",
      "Tenant Isolation",
      "Data Privacy",
      "PDPA-aware Systems",
      "Credential Isolation",
      "Permission Design",
      "Auditability",
      "Audit Trails",
      "Approval Systems",
      "Human Authority",
      "Policy Enforcement",
      "Secure AI Workflows",
      "Prompt Injection Awareness",
      "AI Safety Engineering",
      "Secure Integrations",
      "Firmware inspection",
      "Attack-path analysis",
      "Risk assessment",
      "Rollback design"
    ]
  },
  {
    "id": "14",
    "title": "GOOGLE / BUSINESS SYSTEMS",
    "items": [
      "Google Workspace",
      "Google Admin",
      "Gmail",
      "Google Cloud",
      "Google APIs",
      "Google Maps",
      "Google Reviews",
      "Google Apps Script",
      "Business Automation",
      "SaaS Administration",
      "Internal IT Systems",
      "Account Management",
      "Workspace Automation",
      "Business System Integration",
      "Workspace administration"
    ]
  },
  {
    "id": "15",
    "title": "IT / SYSTEM ENGINEERING",
    "items": [
      "IT Operations",
      "Technical Support",
      "Systems Administration",
      "Windows Administration",
      "Windows Engineering",
      "Windows Optimization",
      "OS-level Optimization",
      "Performance Optimization",
      "PC Optimization",
      "Hardware / Software Interaction",
      "System Diagnostics",
      "Network Troubleshooting",
      "Desktop Troubleshooting",
      "Infrastructure Troubleshooting",
      "Windows OS diagnostics",
      "HID devices",
      "IT support"
    ]
  },
  {
    "id": "16",
    "title": "GAMING / ESPORTS TECHNOLOGY",
    "items": [
      "Gaming Technology",
      "Esports Technology",
      "FPS Optimization",
      "Gaming Performance",
      "Latency Optimization",
      "Input Latency",
      "Windows Gaming Optimization",
      "PC Optimization",
      "Game Performance Analysis",
      "Valorant Optimization",
      "Competitive Gaming Systems",
      "Performance Diagnostics",
      "Latency research",
      "Valorant domain",
      "Esports scouting",
      "Competitive data",
      "Player performance",
      "Game-focused UX",
      "Gaming hardware"
    ]
  },
  {
    "id": "17",
    "title": "RESEARCH / EXPERIMENTATION",
    "items": [
      "Technical Research",
      "AI Research",
      "Applied Research",
      "Experimental Engineering",
      "Model Research",
      "Technology Evaluation",
      "Benchmarking",
      "Comparative Analysis",
      "Data Research",
      "Academic Research",
      "Experimental Design",
      "Research Methodology",
      "Technical Investigation",
      "Proof of Concept",
      "Rapid Experimentation",
      "Research-to-Product"
    ]
  },
  {
    "id": "18",
    "title": "TECHNICAL LEADERSHIP",
    "items": [
      "Technical Leadership",
      "AI Technical Leadership",
      "Architecture Leadership",
      "Technical Strategy",
      "Technical Decision Making",
      "Engineering Planning",
      "Product / Engineering Collaboration",
      "Technical Hiring",
      "Candidate Evaluation",
      "AI Tool Evaluation",
      "Build-vs-Buy Analysis",
      "Technical Documentation",
      "Engineering Standards",
      "Software Engineering Process",
      "AI Development Process",
      "Requirements Traceability",
      "Stakeholder Communication",
      "CEO / Executive Communication",
      "Workshop Facilitation",
      "Knowledge Transfer",
      "Architecture decisions",
      "Technical communication"
    ]
  },
  {
    "id": "19",
    "title": "CREATIVE TECHNOLOGY",
    "items": [
      "Creative Technology",
      "Interactive Art",
      "Interactive Experiences",
      "Digital Art",
      "Generative Art",
      "Experimental Art",
      "Motion Art",
      "Abstract Motion Art",
      "Creative Coding",
      "Digital Storytelling",
      "Interactive Media",
      "Multimedia Production",
      "Visual Experimentation",
      "Creative Direction",
      "Art Direction",
      "Digital Experiences",
      "Experimental Interfaces",
      "AI + Art",
      "AI Creative Tools"
    ]
  },
  {
    "id": "20",
    "title": "VIDEO / FILM / CONTENT",
    "items": [
      "Video Production",
      "Video Editing",
      "Video Direction",
      "Short Film Production",
      "Short Documentary",
      "Documentary Direction",
      "Film Direction",
      "Cinematography",
      "Storyboarding",
      "Visual Storytelling",
      "Video Concept Development",
      "Editing",
      "Post-production",
      "Motion Graphics",
      "Visual Effects",
      "Commercial Video",
      "Advertising Video",
      "Social Media Video",
      "Vlog Production",
      "Vlog Filming",
      "Vlog Editing",
      "Camera Operation",
      "Production Planning"
    ]
  },
  {
    "id": "21",
    "title": "ADVERTISING / CREATIVE MEDIA",
    "items": [
      "Creative Advertising",
      "Ad Creative",
      "Advertising Concepts",
      "Abstract Advertising",
      "Motion Ads",
      "Short-form Ads",
      "Social Media Content",
      "Creative Campaigns",
      "Visual Campaigns",
      "Content Production",
      "Creative Direction",
      "Concept Development",
      "Visual Storytelling",
      "AI-assisted Creative Production",
      "AI Media Automation",
      "Generative Media"
    ]
  },
  {
    "id": "22",
    "title": "MUSIC",
    "items": [
      "Singing",
      "Songwriting",
      "Music Production",
      "Music Arrangement",
      "Vocal Performance",
      "Song Cover Production",
      "Cover Songs",
      "Music Recording",
      "Audio Production",
      "Creative Music",
      "AI-assisted Music Creation",
      "Lyric Writing",
      "Melody Development",
      "Music Video Concepts",
      "Sound / Audio Editing"
    ]
  },
  {
    "id": "23",
    "title": "PHOTOGRAPHY / PRODUCTION",
    "items": [
      "Photography",
      "Video Shooting",
      "Camera Work",
      "Location Shooting",
      "Visual Composition",
      "Lighting",
      "Production Planning",
      "Creative Direction",
      "Editing",
      "Color / Visual Treatment",
      "Content Production"
    ]
  },
  {
    "id": "24",
    "title": "CONTENT CREATION",
    "items": [
      "Vlogging",
      "Content Creation",
      "Storytelling",
      "Video Editing",
      "Short-form Content",
      "Long-form Content",
      "Social Content",
      "YouTube-style Production",
      "Personal Media",
      "Documentary Content",
      "Creative Content Strategy",
      "Content Production Pipeline"
    ]
  },
  {
    "id": "25",
    "title": "DESIGN / MEDIA ARTS FOUNDATION",
    "items": [
      "Media Arts",
      "Media Design",
      "Visual Communication",
      "Graphic Design",
      "Digital Design",
      "Visual Storytelling",
      "Art Direction",
      "Creative Concept",
      "Multimedia Design",
      "Experimental Media",
      "Interactive Media",
      "Digital Production"
    ]
  },
  {
    "id": "26",
    "title": "WORKSHOP / EDUCATION",
    "items": [
      "AI Workshops",
      "Generative AI Workshops",
      "Big Data & AI Workshops",
      "Digital Communication Workshops",
      "Technical Workshops",
      "Corporate Training",
      "Government Training",
      "Workshop Design",
      "Workshop Facilitation",
      "Technical Education",
      "Knowledge Transfer",
      "AI Literacy"
    ]
  },
  {
    "id": "27",
    "title": "PROJECT / DELIVERY",
    "items": [
      "End-to-end Product Delivery",
      "End-to-end Software Delivery",
      "Rapid Prototyping",
      "MVP Development",
      "Production Delivery",
      "Iterative Development",
      "Experiment → Build → Test → Ship",
      "Product Launch",
      "Technical Execution",
      "Cross-disciplinary Delivery"
    ]
  }
];

export type SpotlightSize = "large" | "medium" | "small";
export const capabilitySpotlight: { label: string; size: SpotlightSize }[] = [
  { label: 'AI-Native Engineering', size: 'large' },
  { label: 'UX/UI', size: 'medium' },
  { label: 'Music Production', size: 'small' },
  { label: 'Agent Engineering', size: 'large' },
  { label: 'Product Strategy', size: 'small' },
  { label: 'Vlogging', size: 'small' },
  { label: 'AIDLC', size: 'large' },
  { label: 'Data Engineering', size: 'medium' },
  { label: 'Interaction Design', size: 'small' },
  { label: 'Creative Technology', size: 'large' },
  { label: 'Video Production', size: 'medium' },
  { label: 'Python', size: 'small' },
  { label: 'Document Intelligence', size: 'medium' },
  { label: 'Agent-as-a-Service', size: 'large' },
  { label: 'Research-to-Product', size: 'small' },
  { label: 'Software Architecture', size: 'large' },
  { label: 'Workflow Automation', size: 'medium' },
  { label: 'Photography', size: 'small' },
  { label: 'Product Engineering', size: 'large' },
  { label: 'AI Evaluation', size: 'medium' },
  { label: 'Songwriting', size: 'small' },
  { label: 'AI Workflow Engineering', size: 'medium' },
  { label: 'System Design', size: 'medium' },
  { label: 'Singing', size: 'small' },
  { label: 'Interactive Art', size: 'medium' },
  { label: 'Technical Leadership', size: 'medium' },
  { label: 'Cinematography', size: 'small' },
  { label: 'Context Engineering', size: 'small' },
  { label: 'Web Scraping', size: 'small' },
  { label: 'Prompt Design', size: 'small' },
  { label: 'Motion Graphics', size: 'small' },
  { label: 'Next.js', size: 'small' },
  { label: 'Coding Agents', size: 'small' },
  { label: 'Google Workspace', size: 'small' },
  { label: 'User Flows', size: 'small' },
  { label: 'MCP', size: 'small' },
  { label: 'Ground Truth', size: 'small' },
  { label: 'React', size: 'small' },
  { label: 'Human-in-the-loop', size: 'small' },
  { label: 'Data Pipelines', size: 'small' },
  { label: 'Supabase', size: 'small' },
  { label: 'Agent Orchestration', size: 'small' },
  { label: 'OCR', size: 'small' },
  { label: 'Security Review', size: 'small' },
  { label: 'Cloud Deployment', size: 'small' },
  { label: 'Content Creation', size: 'small' },
  { label: 'Windows Optimization', size: 'small' },
  { label: 'Design Systems', size: 'small' },
  { label: 'TypeScript', size: 'small' },
  { label: 'AI Integration', size: 'small' },
  { label: 'Workshop Facilitation', size: 'small' },
  { label: 'FPS Optimization', size: 'small' },
  { label: 'RPC Analysis', size: 'small' },
  { label: 'Documentary Direction', size: 'small' },
  { label: 'User Journey Mapping', size: 'small' },
];
